apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # App of apps pattern - manages other applications
  project: default

  source:
    repoURL: https://github.com/obiohac/gitops-galaxy
    targetRevision: HEAD
    path: manifests/argocd/applications
    directory:
      include: "*-dev.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  info:
    - name: Pattern
      value: App of Apps
    - name: Description
      value: Central management of all applications
    - name: Repository
      value: https://github.com/obiohac/gitops-galaxy
