apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: backend=your-org/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver:~1.0
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/obiohac/gitops-galaxy
    targetRevision: HEAD
    path: helm/my-app-chart

    helm:
      releaseName: backend
      valueFiles:
      - values.yaml
      - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: "*"
      kind: Secret
      jsonPointers:
        - /data

  info:
    - name: GitHub
      value: https://github.com/obiohac/gitops-galaxy
    - name: Documentation
      value: docs/BACKEND.md
