---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/obiohac/gitops-galaxy
    targetRevision: main
    path: application-chart
    helm:
      releaseName: gitops-app-dev
      values: |
        global:
          environment: development
        namespace:
          name: development
        frontend:
          replicaCount: 1
          image:
            tag: latest
        backend:
          replicaCount: 1
          image:
            tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/obiohac/gitops-galaxy
    targetRevision: main
    path: application-chart
    helm:
      releaseName: gitops-app-staging
      values: |
        global:
          environment: staging
        namespace:
          name: staging
        frontend:
          replicaCount: 2
          image:
            tag: v1.0.0
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 4
        backend:
          replicaCount: 2
          image:
            tag: v1.0.0
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/obiohac/gitops-galaxy
    targetRevision: main
    path: application-chart
    helm:
      releaseName: gitops-app-prod
      values: |
        global:
          environment: production
        namespace:
          name: production
        frontend:
          replicaCount: 3
          image:
            tag: v1.0.0
          autoscaling:
            enabled: true
            minReplicas: 3
            maxReplicas: 10
        backend:
          replicaCount: 3
          image:
            tag: v1.0.0
          autoscaling:
            enabled: true
            minReplicas: 3
            maxReplicas: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
