apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sherlock-app-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      frontend=tumbaoka/sherlock-logs-frontend
      backend=tumbaoka/sherlock-logs-backend
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/frontend.semver.constraint: "~1.0.0"
    argocd-image-updater.argoproj.io/backend.semver.constraint: "~1.0.0"
spec:
  project: default
  source:
    repoURL: https://github.com/obiohac/gitops-galaxy.git
    targetRevision: master
    path: helm-charts/sherlock-app
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true